# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/vibhacse@gmail.com/databricks/Lakeflow_Decalarative_Usecase/lakeflow_declarative_etl_pipeline_medallion1")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM workspace.default.sample_aggregation_lakeflow_declarative_etl_pipeline_medallion1"))

# COMMAND ----------

# MAGIC %sql
# MAGIC use freshcatalog1.freshschema1;
# MAGIC select count(*) from silver_geotag ;
# MAGIC --select count(*) from bronze_geotag1 where (cast(latitude as double) between -90 and 90)
# MAGIC --and (cast(longitude as double) between -180 and 180);
