# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC use mysql_foreign_cat.logistics;
# MAGIC select * from shipments1;

# COMMAND ----------

# MAGIC %sql
# MAGIC USE workspace.default;
# MAGIC select * from import_src_to_bronze;
# MAGIC

# COMMAND ----------

df1=spark.read.csv(path="/Volumes/prodcatalog/logistics/source/logistics_source1.csv",header="true",inferSchema="true")
df2=spark.read.csv(path="/Volumes/prodcatalog/logistics/source/logistics_source2.csv",header="true",inferSchema="true")
uniondf=df1.unionByName(df2,allowMissingColumns=True)

uniondf.write.format("delta").mode("append").saveAsTable("prodcatalog.logistics.newbronze")

# COMMAND ----------

# MAGIC %sql
# MAGIC --use prodcatalog.logistics; --source delta
# MAGIC --select count(*) from newbronze;
# MAGIC
# MAGIC use workspace.default;
# MAGIC select count(*) from src_dt_to_bronze_dt1; --target bronze delta table (continuous etl job run) using readStream
# MAGIC
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC use freshcatalog1.freshschema1;
# MAGIC drop table account;
